### ISSUE TITLE
Suggestion: merge HFunctor into Effect

### ISSUE THREAD

**Issue by mitchellwrosen** [fused-effects/fused-effects#146]
If I'm not mistaken, `HFunctor` and `Effect` are always defined together. It might be useful to just put `hmap`/`fmap'` inside of the `Effect` type class, to reduce the API surface area a bit.

**Comment by robrix** [comment]
Thanks for filing!

Higher-order effects with fixed return types for the higher-order positions admit an `HFunctor` instance but not an `Effect` one:

```haskell
data SomeEffect m k
  = SomeThing (m Int) (Int -> k)
```

While this isn’t super common, it _does_ come up sometimes, and thus these need to be separate.

**Comment by mitchellwrosen** [comment]
Interesting, thanks! I'd love to see an example where that pattern is used at some point.

**Comment by robrix** [comment]
Our main use case is an abstract interpreter, where we use a set of effects to model (among other things) the abstract domain via constructors and eliminators (or abstraction/concretization functions, if you prefer).

E.g. to model functions we provide something like:

```haskell
data Function value m k
  = Abstract Name (m value) (value -> k)
  | Apply value value (value -> k)
```

`value` corresponds to the type of the abstract domain for a given interpretation, and thus is fixed. So we can’t implement `Effect` for this definition of `Function`, because `handle` would need to replace `m value` with `n (f value)`, which is ill-typed for that field.

So the general pattern is that `Effect` requires constructors to be polymorphic in the result type of any embedded (scoped, higher-order) actions; hence why `Reader`’s `Local` and `Error`’s `Catch` existentially quantify over the inner result type.

Early on, I explored parameterizing effects with the type of the functor `f`, and composing said functors together, with the idea that `Abstract` would hold `m (f value)` and `handle` would replace it with `n ((f :.: g) value)` (which is well-typed). Unfortunately, this didn’t work out as planned, and quickly became enormously complicated, so it didn’t make it in.
