### ISSUE TITLE
Suggestion: move Control.Effect.Carrier and Control.Effect.Sum into Control.Effect

### ISSUE THREAD

**Issue by mitchellwrosen** [fused-effects/fused-effects#147]
When implementing a new effect, all three of these modules are necessary - it might be nice to just put all of the functionality into `Control.Effect`, so that the `Control.Effect.*` level of the module hierarchy contains only effects (which `Carrier` and `Sum` are not).

**Comment by robrix** [comment]
I kinda like this, but I had wanted to avoid exporting `:+:` and its constructors from `Control.Effect` since if you’re simply _consuming_ effects (rather than defining them), you never need to use it.

We could still get some of this benefit by migrating/re-exporting the `Sum` stuff from the `Carrier` module. Any thoughts?

**Comment by robrix** [comment]
> > if you’re simply consuming effects (rather than defining them), you never need to use it.
> 
> That's true, but (sorry to nitpick) currently `send` is exported by `Control.Effect`, which I feel is also only useful when defining a new effect, to make smart constructors (in fact, totally separate point, I think it could have an uglier but more explicit name like `injectEffect`, since it's so rarely used).
> 
> Let's see... when using off-the-shelf effects, I believe the only symbols you need are:
> 
> * `Member`
> * `Carrier`
> 
> So another solution might be to put all of the guts/innards required for defining new effects in `Control.Effect`, and simply re-export `Member` and `Carrier` from each of the `Control.Effect.*` modules.
> 
> It has the downside of requiring multiple imports if you are using multiple effects, e.g.
> 
> ```
> import Control.Effect.Reader
> import Control.Effect.State
> import Control.Effect.Pure (run) -- Ouch >_<
> ```
> but I'm used to that from MTL, and I kind of like importing effects one at a time anyway. But the payoff is somewhat small - just a flat, consistent namespace for individual effects - it's not the end of the world if not every module called `Control.Effect.Whatever` corresponds to a distinct effect.

**Comment by robrix** [comment]
> > if you’re simply consuming effects (rather than defining them), you never need to use it.
> 
> That's true, but (sorry to nitpick) currently `send` is exported by `Control.Effect`, which I feel is also only useful when defining a new effect, to make smart constructors (in fact, totally separate point, I think it could have an uglier but more explicit name like `injectEffect`, since it's so rarely used).

Fair point, tho `send` doesn’t conflict with e.g. `GHC.Generics` (unlike `:+:`). If anything I’d suggest this (by itself) means we shouldn’t re-export `send`, not that we _should_ re-export other stuff 😊

> Let's see... when using off-the-shelf effects, I believe the only symbols you need are:
> 
> * `Member`
> * `Carrier`

You also need the smart constructors and run functions.

> So another solution might be to put all of the guts/innards required for defining new effects in `Control.Effect`, and simply re-export `Member` and `Carrier` from each of the `Control.Effect.*` modules.

Sure.

> It has the downside of requiring multiple imports if you are using multiple effects, e.g.
> 
> ```
> import Control.Effect.Reader
> import Control.Effect.State
> import Control.Effect.Pure (run) -- Ouch >_<
> ```

This is already required to use both `Reader` & `State`’s smart constructors/handlers, since those aren’t re-exported.

> but I'm used to that from MTL, and I kind of like importing effects one at a time anyway. But the payoff is somewhat small - just a flat, consistent namespace for individual effects - it's not the end of the world if not every module called `Control.Effect.Whatever` corresponds to a distinct effect.

I like the idea of re-exporting `Member` & `Carrier` from the effect modules, since that would cut down on the imports of `Control.Effect` in modules using but not defining effects.

There are three base cases that I’m aware of:

1. Modules defining effects.
2. Modules using effects.
3. Modules referencing effects (e.g. in type signatures only).

Proposal:

1. Re-export `Control.Effect.Sum` from `Control.Effect.Carrier`, so that modules defining effects only need to import the one module.
2. Re-export the `Carrier` and `Member` class names from the effect modules, so that modules using effects don’t need to import `Control.Effect`. Possibly also `run`.
3. Leave `Control.Effect` more or less as-is, so that modules referencing effects don’t need to import anything else, and don’t get conflicts from e.g. `:+:`.

What do you think?

**Comment by mitchellwrosen** [comment]
I like that :)

**Comment by robrix** [comment]
Adding this to 0.4 as it will break backward compatibility (in the event that anyone is getting `send` from `Control.Effect` instead of `Control.Effect.Sum`).

**Comment by robrix** [comment]
We missed this in 0.4, so moved to 0.5.
