### ISSUE TITLE
(Question) Advice for dealing with multiple `Reader` effects?

### ISSUE THREAD

**Issue by mitchellwrosen** [fused-effects/fused-effects#150]
I'm curious if there is a recommended way of dealing with an effect stack that has many reader-like effects. (In playing around with `fused-effects` in a little web app it seems _most_ of my effects are just a thin wrapper over `ReaderC`).

One solution is to have carriers that incur distinct `Reader` constraints:

```haskell
instance (Carrier sig m, Reader FooEnv sig) => Carrier (FooEff :+: sig) (FooC m)
instance (Carrier sig m, Reader BarEnv sig) => Carrier (BarEff :+: sig) (BarC m)
```

and run them all down one after the other:

```haskell
runReader fooEnv . runReader barEnv
```

Another way is to use `generic-lens` to talk about some `env` that's a product type with a single environment type we care about, in each carrier:

```haskell
instance (Carrier sig m, HasType FooEnv env, Reader env sig) => Carrier (FooEff :+: sig) (FooC env m)
instance (Carrier sig m, HasType BarEnv env, Reader env sig) => Carrier (BarEff :+: sig) (BarC env m)
```

then run them all down at once:

```haskell
data Env = Env { fooEnv :: FooEnv, barEnv :: BarEnv }

runReader env
```

So I suppose my question is - and now I'm realizing I could answer this myself by doing some profiling / core dumping - is one approach preferred over the other specifically wrt. performance?

Thank you very much!

**Comment by robrix** [comment]
I haven’t done any profiling of this specific thing, so I’d be very interested in your findings if you should do so, but our use has thus far used separate `Reader` effects almost exclusively, and (anecdotally) we don’t have any complaints thus far.

One reason we’ve used this approach is that if the env type is polymorphic, it’s much more convenient than asking for one part of a composite structure, e.g. `ask @(Foo foo)` rather than `asks @(Foo foo, Bar bar) fst`. Another is that since `ReaderC` is more or less just a function, I’d expect `ghc` to be able to optimize it fairly effectively—tho again, this conjecture currently lacks any profiling to back it up.

Further, if you intend for `FooEnv` to be an implementation detail of `FooC`, you can improve its abstraction by nesting the `ReaderC` inside of `FooC`:

```haskell
newtype FooC m a = FooC { runFooC :: ReaderC FooEnv m a }
``` 

This prevents other code from using the `Reader FooEnv` effect behind the `Carrier` instance’s back, while still allowing convenient usage of the effect within the `Carrier` instance. Note that this couples `FooC` to the specific `Reader` semantics of `ReaderC`, and thus is inappropriate in cases where you consumers should be able to vary the behaviours of these effects orthogonally/compositionally.

**Comment by patrickt** [comment]
My take on this is that multiple `Reader` constraints are better than a composite data type used for `Reader` + the classy-lenses idiom. Decomplecting the types provided by  `State`/`Reader` constraints can make it more immediately apparent which parts of your program are using which parts of the context and state. This encourages a more granular approach to program structure and makes adding one-off constraints within an effect stack - i.e. adding an inline `runReader` invocation to avoid passing arguments explicitly - more fluid than rather than having to retrace one’s steps back to a monolithic context type to which one must add a field.

**Comment by robrix** [comment]
Great points, @patrickt ✨

**Comment by patrickt** [comment]
I'm closing this, since there doesn't seem to be any actionable items in this issue. Feel free to reopen it should this change.
