### ISSUE TITLE
Carrier is a poor name for the typeclass

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#216]
“Carrier” is a pretty opaque word, and doesn’t communicate much about the typeclass or its method.

By contrast, “Algebra” is, while still somewhat opaque, at least better-recognized in circles exposed to recursion schemes, and relates the purpose of the class quite clearly. It’s also got precedent in the literature (hello `TermAlgebra`), and philosophically, hews more to the category theoretical: focus on the morphisms, not the objects.

**Comment by robrix** [comment]
I propose we rename `Carrier` to `Algebra`, including moving all the `Control.Carrier.*` modules to `Control.Algebra.*`. Informally, referring to individual types as carriers (note the lowercase) is still appropriate (they’re certainly not algebras), so docs will need to distinguish between uses of the word referring to the class and uses referring to the type.

**Comment by robrix** [comment]
I also propose renaming `eff` to `alg` at the same time.

**Comment by patrickt** [comment]
I still haven’t overcome my reluctance to rename `Carrier`. I think its name is quite valuable now—it implies a sort of conveyance, a ferrying of effects to a monadic stream down below, and I think it suggests quite vividly what its purpose is at a glance. Certainly it _is_ an algebra, and we should note as such in the definition, and see what kind of properties we can get out of calling it an algebra. But at the end of the day I think this class is of such fundamental importance that it’s better that its name stems from its purpose, rather than its nature.

**Comment by robrix** [comment]
But it’s the type that’s the carrier, not the instance. The name confuses things by conflating the two.

**Comment by jkachmar** [comment]
Comparing the following comment for the `Carrier` typeclass defines here:
> The class of carriers (results) for algebras (effect handlers) over signatures (effects), whose actions are given by the 'eff' method.

...with the comment for the `Algebra` typeclass defined in `diffused-effects`:
> The class of algebras (effect handlers) for carriers (monad transformers) over signatures (effects), whose actions are given by the 'alg' method.

...makes me think that there’s some distinction that could stand to be elucidated up upon.

If I’m understanding the relationship correctly here, it does seem that naming the class `Carrier` and referring to the newtypes as effect Carriers makes things less clear than they ought to be.

On the other hand, I find the name `Algebra` to be a bit intimidating. However, I think this is something that could be addressed by adding some documentation to the module explaining the algebraic nature of the class and it’s instances (or linking to some external documentation that covers the same ground). Or... really any kind of prior art at all that might make the usage of the term `Algebra`* that much clearer to the layperson.

* I really just wanted to say “term algebra” here, since Rob’s earlier comment made me go read up on exactly what that means, sorry.

**Comment by zenzike** [comment]
I think that `Algebra` is more appropriate, along with `alg`. This puts things more in line with the literature. The point of the class is to introduce the function of type `sig m a -> m a`, which to me is clearly an algebra.

**Comment by patrickt** [comment]
After a convo with Rob, I’m withdrawing my objection too—we’ve decided not to move the entire `Control.Carrier.*` hierarchy. We will instead move `Control.Carrier.Class` to `Control.Algebra` (once #281 lands) and rename the `Carrier` class to `Algebra`; the `Carrier` nomenclature remains in the module hierarchy, which is where it ought to live.

**Comment by jkachmar** [comment]
A former coworker gave me a brief explanation and pointed me towards some resources that helped me understand the algebraic nature of the class.

---

Perhaps this is out-of-bounds for this issue thread, but I think it would be helpful to have either a summary of useful terminology in the Haddocks and/or links to threads (like this one) that explain some of the naming/design choices in the library.

**Comment by patrickt** [comment]
> I think it would be helpful to have either a summary of useful terminology in the Haddocks and/or links to threads (like this one) that explain some of the naming/design choices in the library.

I strongly agree. I intend to address that in #271.
