### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by iand675** [fused-effects/fused-effects#240]
Not the usual sort of issue, sorry if it's extra noise. But just wanted to say I've started building some tools with fused-effects and it's solving a lot of mtl pain points really well. Docs are maybe still a little sparse, but the fused-effects team has clearly come up with a great solution!

![great](https://media.giphy.com/media/wUm7SnqJIA8AE/giphy.gif)

:tada:

**Comment by robrix** [comment]
Thank you so much! 💖 That’s incredibly kind of you to say!

> Docs are maybe still a little sparse

Docs are actually one of the things we’re focusing on improving for 1.0; are there any particular gaps you’d like to see covered?

**Comment by iand675** [comment]
Maybe it's best to share my confusion points and where I arrived after fiddling, and you can use that to inform documentation.
 
I guess the confusion is around discharging local effects without leaking concrete implementation details?

Essentially I have a problem domain where I'm scanning over a provided schema and using it to do some codegen a la `amazonka`. I had the notion of having a hierarchy of contexts, where each context added some additional context to its parent context:

RootSig > ConstructorSig > FieldSig

So the idea would be defining functions vaguely like the following:

``` haskell
-- Wiring up the Carrier __ n part here got weird
traverseConstructors :: (Monad m, Monad n, RootSig sig, Carrier sig m) => 
     (Constructor -> n a) 
  -> m (TypeConversions, [a])
```

However, I got a little stuck defining that function as it appears that actually *running* f necessitates making the effect structure concrete:

``` haskell
traverseConstructors :: (Monad m, RootSig sig, Carrier sig m) =>
     (Constructor -> StateC TypeConversions m a) 
  -> m (TypeConversions, [a])
traverseConstructors f = do
  cs <- asks schemaConstructors
  runState emptyTypeConversions $ mapM f cs
```

At that point it sort of feels like I'm losing the nice abstract type signatures and having to make the signatures more concrete than the `fused-effects` library intends, but I'm not certain whether I'm "doing it right" or not.

**Comment by patrickt** [comment]
@iand675 Thank you so much for your kind words!

You are right in that sometimes implementation details necessitate a concrete stack of carrier monads. This is not necessarily a bad thing—after all, that’s normal in `mtl`. We do so in `semantic` in a [few places](https://github.com/github/semantic/blob/e96832f61e1fca78cbf12c9951d9c002d7acdb4e/src/Reprinting/Translate.hs#L21).

I agree that it’s not always the nicest thing, though, especially when it’s inferable from the surrounding context. I think this is an appropriate use case for `PartialTypeSignatures`: you could write 

```haskell
traverseConstructors 
  :: (Monad m, RootSig sig, Carrier sig m)
  => (Constructor -> _ m a)
  -> m (TypeConversions, [a])
```

**Comment by iand675** [comment]
![alright](https://media.giphy.com/media/1xl9zvlxnIlQnzUtyW/giphy.gif)

The partial type signature seems like what I'm looking for here, cheers.

**Comment by robrix** [comment]
Sorry for the delay in responding! I wanted to add a comment to @patrickt’s note on partial type signatures: while partial type signatures hide the carrier type from the _reader_, they certainly don’t hide it from the typechecker, and so you can still pass in actions which depend on the concrete monad stack employed.

This is kind of a funny corner: `fused-effects`’ whole schtick is that your monadic actions should be written abstractly, and interpreted concretely; so the `Constructor -> …` action you pass in is probably actually something like:

```haskell
foo :: (Member (State TypeConversions) sig, Carrier sig m) => Constructor -> m a
```

which enjoys the abstraction provided by the effect signature (the “written abstractly” part of the slogan). Mentioning `StateC` could be seen as simply the “interpreted concretely” part of the slogan, but on the other hand, it definitely allows consumers to couple to the implementation detail—the carrier—and probably more than one intended. It’s easy to say “then don’t do that,” but we’d like to provide compiler-enforced _guarantees_, that’s one of the reasons we use Haskell.

When I want to guarantee that a higher-order function is limited in what I can do, I reach for parametricity—the same essential trick used by PHOAS, structured graphs, and other approaches. Specifically, rank-n types allow us to say that the argument must operate in (e.g.) absolutely _any_ `Carrier` n for a given signature, going from this (using the new constraints available on `master`):

```haskell
f :: Has (Reader Int) sig m
  => (Int -> StateC String m a)
  -> m (String, a)
f g = ask >>= runState "" . g
```

to this:

```haskell
f :: Has (Reader Int) sig m
  => (forall n . Int -> n a)
  -> m (String, a)
f g = ask >>= runState "" . g
```

This is now _under_-constrained, in that there’s nothing useful you can do in that function unless you know more about `n`. We can give it more latitude with constraints:

```haskell
f :: Has (Reader Int) sig m
  => (forall n . Monad n => Int -> n a)
  -> m (String, a)
f g = ask >>= runState "" . g
```

but this still doesn’t allow it to perform effects (mostly it just allows `return`!). For that, we need a `Carrier` instance, but that won’t suffice—we probably also want it to be able to inherit any effects from the context that `f` is being called within. `n` can’t be a `Carrier` for `sig`, because that’s the (weaker) signature above where the function is called. Explicitly listing effects available in the calling context would work:

```haskell
f :: (Has (Reader Int) sig m, Effect sig)
  => (forall n sig' . Has (Reader Int) sig' n => Int -> n a)
  -> m (String, a)
f g = ask >>= runState "" . g

x :: (Has (Reader Int) sig m, Effect sig) => m (String, Bool)
x = f (asks . (==))
```

but would couple `f` much too tightly to said context, and is really only suitable when you want to only whitelist a few effects. So while we can’t use the same `sig` as the outer context, we also don’t want a completely _unrelated_ signature; we need it to be a signature connected to the outer one, for example:

```haskell
f :: (Has (Reader Int) sig m, Effect sig)
  => (forall n eff . Carrier (eff :+: sig) n => Int -> n a)
  -> m (String, a)
f g = ask >>= runState "" . g
```

However, now `x` can’t be sure of what `eff` is—if it has to typecheck for _all_ effects `eff`, then it has to work if `eff` is, for example, the `Reader Int` effect it was trying to inherit from its environment:

```haskell
x :: (Has (Reader Int) sig m, Effect sig) => m (String, Bool)
x = f (asks . (==))
```

```
    • Overlapping instances for Control.Effect.Sum.Member
                                  (Reader Int) (eff :+: sig)
        arising from a use of ‘asks’
```

For this to typecheck, we need to surface _some_ information about `eff`, for example that it’s a `State` effect:

```haskell
f :: (Has (Reader Int) sig m, Effect sig)
  => (forall n s . Carrier (State s :+: sig) n => Int -> n a)
  -> m (String, a)
f g = ask >>= runState "" . g

x :: (Has (Reader Int) sig m, Effect sig) => m (String, Bool)
x = f (asks . (==))
```

This works! We no longer allow the higher-order function visibility into which carrier is selected, and all it took was `-XRankNTypes`. However, if there were an underlying `State` effect which `x` wanted to use in the function passed to `f`, it’d be back in the same boat:

```haskell
x :: (Has (Reader Int) sig m, Has (State Char) sig m, Effect sig) => m (String, String)
x = f (gets . replicate)
```

```
    • Overlapping instances for Control.Effect.Sum.Member
                                  (State Char) (State s :+: sig)
        arising from a use of ‘gets’
```

because `State s`, where `s` is universally quantified, could be instantiated to `State Char`, and intercept the request made by `gets`. For this to work, we have to be more specific about the state type:

```haskell
f :: (Has (Reader Int) sig m, Effect sig)
  => (forall n . Carrier (State String :+: sig) n => Int -> n a)
  -> m (String, a)
f g = ask >>= runState "" . g
```

This, at last, works. Now the _only_ effect requests that could be intercepted are those for `State String`, but we’re not giving the higher-order function any indication as to what the monad stack is: while `n`’s _signature_ is connected to `m`’s, `n` is not connected to `m`. And if we want to be slightly more abstract and guarantee that the higher-order function can’t mess with our `String`, we could abstract it using a `newtype` without exporting its constructor or selector.

But there are other options, too, e.g. holding `eff` abstract but allowing the function to `lift` requests for effects:

```haskell
f :: (Has (Reader Int) sig m, Effect sig)
  => (forall eff t . (MonadTrans t, Carrier (eff :+: sig) (t m)) => Int -> t m a)
  -> m (String, a)
f g = ask >>= runState "" . g

x :: (Has (Reader Int) sig m, Effect sig) => m (String, Bool)
x = f (lift . asks . (==))
```

or hiding it completely behind a new carrier which doesn’t extend the signature (sort of an abstracted version of the above technique which doesn’t require the function to use `lift`):

```haskell
f :: (Has (Reader Int) sig m, Effect sig)
  => (forall n . Carrier sig n => Int -> n a)
  -> m (String, a)
f g = ask >>= runState "" . runStatelyC . g

newtype StatelyC m a = StatelyC { runStatelyC :: StateC String m a }
  deriving (Applicative, Functor, Monad)

instance (Carrier sig m, Effect sig) => Carrier sig (StatelyC m) where
  eff = StatelyC . eff . R . handleCoercible

x :: (Has (Reader Int) sig m, Effect sig) => m (String, Bool)
x = f (asks . (==))
```

or even defining a new effect type wrapping `State`, and a new carrier for it, but not exporting it.

Ultimately, the key to all of these approaches is polymorphism—rank-n types.

But at the end of the day, I _usually_ just write `(Constructor -> StateC TypeConversions m a)` and be done with it.
