### ISSUE TITLE
Should `modify` be a constructor of the State effect?

### ISSUE THREAD

**Issue by patrickt** [fused-effects/fused-effects#252]
For a long time, our `modify` has been strict and implemented in terms of `get`, `put` and `$!`, and we’ve provided a `modifyLazy` function that behaves like `modify` from `mtl`. This incongruity (two functions that do the same thing, kind of) makes me think that carrier should define `modify`. This would be a break from the tradition set down by `mtl`, which only has `get` and `put` in its `MonadState` class, but it would enable an interesting use case: an `AtomicState` class that used a `TVar` or `IORef` to make updates and accesses to the state truly atomic. (This is not possible unless `modify` lives in `State`, because otherwise `gets f >>= put` allows for a race condition in between the `gets` and `put`).

Thoughts?

**Comment by robrix** [comment]
1. I’m not super fond of the idea that `get`/`put` could be inconsistent with `modify`. On the other hand, that’s the job of laws (cf #169, #239) to sort out, so maybe not a big deal?

2. I don’t think the selection of `modify` vs. `modifyLazy` is 100% related to the selection of `Strict.StateC` vs. `Lazy.StateC`; the former provide strict and lazy application of the higher-order function, respectively; the latter strict and lazy `>>=`. Thus, I think making it equivalent to the selection of the carrier would be a mistake. (I actually also wonder whether `modifyLazy` should exist at all, but that’s another question altogether.)

3. That race condition is always going to exist with `State`, because it exists with `do { s <- get ; s' <- … ; put s' }`. Atomic access to one variable does not imply atomic computations involving that variable, and so I think it’s the wrong level of granularity to provide that sort of functionality at. Instead, we should look at how we can best integrate with STM, since unlike atomic reads/writes on a single variable, STM is composable.

Overall, I’m 👎

**Comment by patrickt** [comment]
After some polls of the populace, I’m withdrawing this. People who need an atomic state change operation can write their own effect and use it in conjunction with `:+: State`.
