### ISSUE TITLE
Request for docs: Manual implementation of Effect instances

### ISSUE THREAD

**Issue by iand675** [fused-effects/fused-effects#289]
I've got a kind of hairy wrapper around some database query DSLs, and the `Effect` class is not automatically derivable due to some existentials. The docs don't really give me a good intuition around how the threading of effects is supposed to be done correctly. It might help to elaborate a bit on what the correct laws are for threading?

Minimal example to illustrate my confusion:

``` haskell
data RunDB backend m k
  = forall a . AttachName Text (backend -> m a) (a -> m k) 
  -- ^ passing a through from inner function 
  | forall a r . SqlSelect a r => Select_ (SqlQuery a) ([r] -> m k)
  -- ^ Weird one, [r] originates from an existentially quantified class
  --  / callback function type sig
  | Delete_ (SqlQuery ()) (m k)
  -- ^ Does the action that is the second argument need to do anything with state?
  | DeleteCount_ (SqlQuery ()) (Int64 -> m k) 
  -- ^ How about now
```

I'm hoping the when, why, & how to use the `f ()` argument of `handler` can be elucidated just a bit. Hope that makes sense!

![confuse](https://media.giphy.com/media/Csj3geMlq14ZO/giphy.gif)

**Comment by robrix** [comment]
Great idea—we should definitely document this more thoroughly.

In the meantime, a quick overview (which might motivate me to extract it into the docs), motivating the method from the `Algebra` instances using it:

Let’s say you have `Reader r` and `State s` effects in scope, carried by `StateC s (ReaderC r PureC)`. `StateC`’s `Algebra` instance (the 1.0 name for what used to be `Carrier`) has to interpret the entire signature of `State s :+: Reader r :+: Pure`, but it only knows about the `State s` part itself. `:+:` has two constructors, `L` and `R`, so if it gets an `L`, that holds a `State s`, and it can interpret that directly. If it gets an `R`, it instead delegates that to the next `Algebra` instance—in this case, the one for `ReaderC r PureC`:

```haskell
instance (Algebra sig m, Effect sig) => Algebra (State s :+: sig) (StateC s m) where
  eff (L (Get   k)) = StateC (\ s -> runState s (k s))
  eff (L (Put s k)) = StateC (\ _ -> runState s k)
  eff (R other)     = …
```

To do so, it needs to pass it a signature of the correct type; in general for `State s :+: sig` & `StateC s m`, that’s `sig m a`, and for our specific case that instantiates to `(Reader r :+: Pure) (ReaderC r PureC) a`. But what it _has_ is `sig (StateC s m) a` (which instantiates to `(Reader r :+: Pure) (StateC s (ReaderC r PureC)) a`):

```haskell
eff (R other) = StateC (\ s -> eff (… other))
```

In general, `StateC s`’s `Algebra` instance doesn’t know anything about the next carrier or what effect it handles. If it’s a higher-order effect—like `Reader`’s `Local` constructor, which embeds an action—then it can’t just unwrap the `StateC s m` to get an `m`; `StateC s m` is a `newtype` wrapping `s -> m (s, a)`. The `s` inputs and outputs need to be accounted for, and that’s where `Effect` comes in:

```haskell
eff (R other) = StateC (\ s -> eff (handle … … other))
```

`Effect` allows an effect datatype to plumb a handler function—like `runState` or `runError`—through an effect constructor, starting with some initial state and preserving that state the whole way along.

```haskell
  handle :: (Functor f, Monad m)
         => f ()
         -> (forall x . f (m x) -> n (f x))
         -> sig m a
         -> sig n (f a)
```

The `f ()` parameter is the `Algebra`-determined initial state value. For `StateC s`, we need `f` to incorporate the state at the point at which `eff` is being run, so we instantiate `f` to `(,) s` and construct `(,) s ()` as a literal tuple:

```haskell
eff (R other) = StateC (\ s -> eff (handle (s, ()) … other))
```

The next parameter is a handler of type `forall a . f (m a) -> n (f a)`, i.e. taking a monadic action bundled up with some state, and returning a new action containing the new state, for any result type `a`. Often, `m` will be a monad transformer like `StateC s m` and `n` will be the underlying monad, but the type doesn’t enforce this. For our case, it instantiates to `forall a . (s, StateC s m a) -> m (s, a)`, which in a particularly beautiful not-at-all-coincidence is the type of `uncurry runState`:

```haskell
eff (R other) = StateC (\ s -> eff (handle (s, ()) (uncurry runState) other))
```

As a brief aside, we couldn’t use `forall a . f () -> m a -> n (f a)`, because that wouldn’t work for something like `ErrorC e` which instantiates `f` to `Either e`. `ErrorC e` actions can terminate due to `throwError`, so there might not actually _be_ an `m a` to run, and so these handler functions need to accommodate that fact.

In our example, as discussed above, the call to `eff` goes to the `Algebra` instance for `ReaderC r PureC`, and `other` is `Reader r :+: Pure`. Let’s suppose that the specific value of `other` is `L (Ask k)`; `:+:`’s `Effect` instance simplify delegates `handle` on to its members and wraps them back up, so we end up in `Reader`’s `Effect` instance, shown with the types instantiated:

```haskell
handle
  :: (s, ())                                                                  -- ^ state
  -> (forall a . (s, StateC s (ReaderC r PureC) a) -> ReaderC r PureC (s, a)) -- ^ handler
  -> Reader r (StateC s (ReaderC r PureC)) a                                  -- ^ (Ask k)
  -> Reader r (ReaderC r PureC) (s, a)
handle state handler (Ask k) = …
```

`handle` must always return the _same_ effect constructor as was passed in, so we can specialize that a bit further:

```haskell
handle state handler (Ask k) = Ask …
```

`Ask`’s continuation `k` has the type `(r -> StateC s (ReaderC r PureC) k)`, and we need `(r -> ReaderC r PureC (s, k))`. `handler` is our only means of eliminating the `StateC` in the result of the continuation, so we need to use that; but it also requires its action to be embedded in some current state. Therefore, we first need to wrap the result of the continuation up in `(,) s`, which we get from our initial `state` to arrive at the definition:

```haskell
handle state handler (Ask k) = Ask (handler . (<$ state) . k)
```

First-order effect constructors embed continuations as `m k`, and thus all have structure very similar to this; take for example `Tell` from `Writer`:

```haskell
handle state handler (Tell w k) = Tell w (handler (k <$ state))
```

The only difference here is that the `m k` is embedded directly, rather than being the result of a function, so we can lift `k` into `state` directly rather than via function composition.

Now let’s suppose that the value of `other` had been `L (Local f m k)`; again, `:+:` delegates to `Reader r`, so we end up here (with the same instantiated types as before):

```haskell
handle state handler (Local f m k) = Local f (handler (m <$ state)) (handler . fmap k)
```

This is where the correct handling of the `state` variable becomes important. We use `state` when handling the embedded action `m`, but for the continuation `k`, we instead rely on the fact that `handler` returns a `ReaderC r PureC (s, a)`—i.e. an action potentially with _new_, distinct state. Thus, if `m` had performed a `put`, any changes it made would be correctly propagated to the continuation after `local`. Similarly, if `handler` were eliminating `ErrorC e`, the effect of a `throwError` occurring in `m` would be propagated to the continuation as well, rather than us incorrectly attempting to resume the continuation.

This is the typical pattern for higher-order effect operations like `Local`, but it’s not the only one; another elucidating example is `Catch`, which has _two_ higher-order actions:

```haskell
handle state handler (Catch m h k) = Catch (handler (m <$ state)) (handler . (<$ state) . h) (handler . fmap k)
```

Note that this uses `state` twice: once for handling `m`, and once for handling the result of `h`. Intuitively, this tells us that the error handler `h` is a _replacement_ for the action `m` in the event that `m` fails, and not e.g. a continuation _after_ it. Otherwise put, `Catch` selects the result of _at most one_ of `m` and `h` to pass to its continuation. Thus, effects allow us to specify a variety of useful control flow mechanisms, and `handle` is responsible for the important, if somewhat mechanical, job of plumbing the results of earlier carriers through.

**Comment by robrix** [comment]
> ```haskell
> data RunDB backend m k
>   = forall a . AttachName Text (backend -> m a) (a -> m k) 
>   -- ^ passing a through from inner function 
>   | forall a r . SqlSelect a r => Select_ (SqlQuery a) ([r] -> m k)
>   -- ^ Weird one, [r] originates from an existentially quantified class
>   --  / callback function type sig
>   | Delete_ (SqlQuery ()) (m k)
>   -- ^ Does the action that is the second argument need to do anything with state?
>   | DeleteCount_ (SqlQuery ()) (Int64 -> m k) 
>   -- ^ How about now
> ```

At a quick glance, it looks like `AttachName` is higher-order, but the rest are all first-order, which makes this fairly mechanical, if non-obvious: there is exactly one instance that will typecheck; and it will use the initial `state` parameter exactly once per constructor, and `handler` twice for `AttachName` but only once for the rest (otherwise put, once per `m` in any constructor).

The laws governing `handle` &c. are described in _Effect Handlers in Scope_, which I can dig up for you later if you’d like; we should definitely document them.
