### ISSUE TITLE
Rename "thread" again?

### ISSUE THREAD

**Issue by mitchellwrosen** [fused-effects/fused-effects#313]
I just updated a little side project to fused-effects HEAD and found myself writing this in a few places:

![2019-10-29-012220_454x28_scrot](https://user-images.githubusercontent.com/1074598/67740003-b6707e80-f9ea-11e9-8443-f8e44e345243.png)

It's a slack bot, so I have a few variables named "thread" that refer to chat threads. I've also named `ThreadId`s "thread" before. I wonder if "thread" is too short/common of a name for the `Effect` method, which usually does not have to be called directly nor defined manually. Perhaps it could have a longer, non-noun name like "threadEffectState"?

**Comment by robrix** [comment]
Thinking aloud, we probably don’t want to restrict the re-export of `Effect` from `Control.Algebra` (e.g. to hide the method), because then nearly every carrier and effect module will have to add an extra import of `Control.Effect.Class`.

On the other hand, I’m curious what kind of modules you’re importing `Control.Algebra` into rather than one of the effect or carrier modules? I’d have thought the re-exports of `Algebra`, `Has`, and `run` from the effect (and thus carrier) modules would have obviated the need for that.

**Comment by patrickt** [comment]
> I could also re-export these symbols from my custom /carrier effect modules.

I'd say that's the way to go 👍

**Comment by robrix** [comment]
@mitchellwrosen Did you close this because you didn’t need so many imports, or…? Cos if this is still a problem then I’d still be in favour of addressing it for 1.0.

**Comment by mitchellwrosen** [comment]
Oh, sorry! I closed because @patrickt's solution works for me. But please reopen if there's anything to do on your end.
