### ISSUE TITLE
Can carriers really "handle more than one effect"?

### ISSUE THREAD

**Issue by danidiaz** [fused-effects/fused-effects#324]
Hi,

I'm a bit confused by the following sentence of the documentation:

> **Carriers can handle more than one effect**, and multiple carriers can be defined for the same effect, corresponding to different interpreters for the effect’s syntax.

My confusion stems from the fact that the `Carrier` typeclass has a functional dependency:

    class (HFunctor sig, Monad m) => Carrier sig m | m -> sig

The carrier fixes the signature. Doesn't that forbid carriers that handle more than one effect?

**Comment by danidiaz** [comment]
Actually, I'm dumb. I was looking and the README in the GitHub repo, but the actual documentation in Hackage for version 0.5.0.1 states that:

> Each carrier handles one effect, but multiple carriers can be defined for the same effect

**Comment by patrickt** [comment]
There is only one `Algebra` instance per carrier, but carriers can handle multiple (zero or more, technically) effects. Consider the `NonDetC` carriers in `Control.Carrier.NonDet.Church`, which handles `Choose :+: Empty`.

**Comment by robrix** [comment]
They can also handle zero effects, but that’s usually done to build e.g. wrappers with phantom types for inference purposes.

Since an algebra will generally call `alg` for some underlying carrier `m`, it’s actually handling the _entire_ signature, it’s just that it’s delegating handling the tail of the signature via `m`.
