### ISSUE TITLE
Need raise operation to introduce new effect

### ISSUE THREAD

**Issue by mikesperber** [fused-effects/fused-effects#358]
I want to inject a "new" effect into a computation. Polysemy has this function, which is exactly what I need:

`raise :: forall e r a. Sem r a -> Sem (e ': r) a `

I couldn't find anything that will let me do it in `fused-effects` - help would be much appreciated!

**Comment by robrix** [comment]
I believe that’s `lift` from `transformers`.

**Comment by robrix** [comment]
(IIRC, all of the carriers we define have `MonadTrans` instances.)

**Comment by mikesperber** [comment]
I probably haven't thought this through, but I want to introduce a new effect into the *signature* - I don't want to specify the implementation at this point.

**Comment by robrix** [comment]
@mikesperber: I might be missing some exigencies of your use case, so sharing more details would be helpful. But I believe you can accomplish the above using `MonadTrans`:

```
raise :: (MonadTrans t, Algebra sig m, Algebra (eff :+: sig) (t m)) => m a -> t m a
raise = lift
```

(The `Algebra sig m` constraint might be redundant, I haven’t checked.)

That said, I think “introducing a new effect into the signature” isn’t really the best way of thinking about `fused-effects`. Performance concerns mean that generally you _do_ want to specify the implementation at the point at which you handle an effect; the library is in fact designed around this idea. When decoupling from some specific implementation is paramount, however, one can achieve precisely this with [careful application of `RankNTypes`](https://github.com/fused-effects/fused-effects/issues/240#issuecomment-537048365). (I keep meaning to turn that into a blog post…)

**Comment by mikesperber** [comment]
@robrix Thanks for the instant turnaround on this, and for the explanation. That helps me understand where `fused-effects` is coming from!

I was able to make your first suggestion work, but not the second. (Mainly because `(MonadTrans t, Monad m) => Monad (t m)` does not hold.)

If you're interested, the code in question is here:

https://github.com/mikesperber/haskell-effects-tutorial

There, I tried to do a simple discrete-event simulator with different approaches to controlling the effects.

The `fused-effects` version is here:

https://github.com/mikesperber/haskell-effects-tutorial/blob/master/src/DES/FusedEffects.hs

The problem here is that there are two layers of effects, and computations with the lower-level effect are embedded in the higher-level effect. I need `raise` to embed the lower-level computation into the higher-level ones.

**Comment by robrix** [comment]
> @robrix Thanks for the instant turnaround on this, and for the explanation. That helps me understand where `fused-effects` is coming from!
> 
> I was able to make your first suggestion work, but not the second. (Mainly because `(MonadTrans t, Monad m) => Monad (t m)` does not hold.)

Yeah, you’d also need `QuantifiedConstraints` and `forall n . Monad n => Monad (t n)` for that, I suppose. Although now that I try it, commenting out the other definition does seem to work?

```haskell
raise :: (MonadTrans t, Algebra sig m, Algebra (eff :+: sig) (t m)) => m a -> t m a
raise = lift
```

(Note that this doesn’t require a `Monad (t m)` constraint because it’s implied by the second `Algebra` constraint.)

> There, I tried to do a simple discrete-event simulator with different approaches to controlling the effects.
> 
> The `fused-effects` version is here:
> 
> https://github.com/mikesperber/haskell-effects-tutorial/blob/master/src/DES/FusedEffects.hs
> 
> The problem here is that there are two layers of effects, and computations with the lower-level effect are embedded in the higher-level effect. I need `raise` to embed the lower-level computation into the higher-level ones.

Yeah, embedding computations in state fields (`SimulationStateEffect`) is always a bit complicated, both because it makes the constraints _much_ more brittle, and because the “obvious” approach to factoring it into a `State`-like effect loses covariance (and thus isn’t a valid `HFunctor`).

I try never to have `Has (State (Blah m)) sig m`, either by abstracting the use of `m` behind another (by definition, higher-order) effect, or by rearchitecting to not need to store computations in the first place unless I actually need to use them as coroutines or for other “weird” control flow purposes. The higher-order effect route is actually precisely what higher-order effects are _for_, and allows you to e.g. run other effects above the higher-order one without worrying about brittleness at all.

**Comment by mikesperber** [comment]
@robrix Huh, you're right. Dunno what changed.

Many thanks for the timely and deep advice on this!
