### ISSUE TITLE
Why is alg taking 3 arguments in the defining_effects.md?

### ISSUE THREAD

**Issue by poscat0x04** [fused-effects/fused-effects#378]
I'm confused by the documentation of [defining effects](https://github.com/fused-effects/fused-effects/blob/master/docs/defining_effects.md).  
In the "Defining algebras" section, the `alg` implementation for `Teletype` is taking 3 arguments `hdl`, `sig`, `ctx`:
```Haskell
instance (MonadIO m, Algebra sig m) => Algebra (Teletype :+: sig) (TeletypeIOC m) where
  alg hdl sig ctx = case sig of
    L Read      -> (<$ ctx) <$ liftIO getLine
    L (Write s) -> ctx      <$ liftIO (putStrLn s)
    R other     -> TeletypeIOC (alg (runTeletypeIO . hdl) other ctx)
```
But `alg` only has an arity of 1 according to [haddock](https://hackage.haskell.org/package/fused-effects-1.0.2.0/docs/Control-Algebra.html#v:alg), and the rhs of the function arrow (`TeletypeIOC m a` in this case) dosn't expand to functions either

**Comment by poscat0x04** [comment]
Tried to rewrite the example using freer-monad style effects
```
data Teletype (m :: Type -> Type) k where
  Read  :: (String -> m k) -> Teletype m k
  Write :: String -> m k -> Teletype m k

newtype TeletypeIOC m a = TeletypeIOC { runTeletypeIO :: m a }
  deriving (Applicative, Functor, Monad, MonadIO)

instance HFunctor Teletype where
  hmap f (Read c) = Read (\s -> f (c s))
  hmap f (Write s c) = Write s (f c)

instance (MonadIO m, Algebra sig m) => Algebra (Teletype :+: sig) (TeletypeIOC m) where
  alg sig = case sig of
    L (Read  c) -> liftIO getLine >>= c
    L (Write s c) -> liftIO (putStrLn s) >> c
    R other     -> TeletypeIOC (alg (hmap runTeletypeIO other))
```

**Comment by rl-king** [comment]
You're looking at master branch which has some [changes](https://github.com/fused-effects/fused-effects/blob/master/ChangeLog.md) for upcoming release. 

This is the same example but for the current release `1.0.2.0` https://github.com/fused-effects/fused-effects/blob/1.0.2.0/examples/Teletype.hs

**Comment by poscat0x04** [comment]
oof. This seems to be a pretty huge change.

**Comment by robrix** [comment]
@poscat0x04:

> oof. This seems to be a pretty huge change.

Yes, it is a significant breaking change for 1.1. On the other hand, here’s some of what it buys us:

- you don’t need an `HFunctor` or `Effect` instance for any effect any more (in fact, the classes are altogether gone);

- that in turn has allowed us to migrate to GADTs representations for the effects, which means there are no more continuations to worry about in the effects, which simplifies algebras significantly;

- it should make for a small speedup since we no longer have to change the effect data at all, tho I should note I haven’t yet measured this as a significant factor.

It will require changes to `Algebra` instances and effect definitions, but IMO it’s a pretty substantial improvement.

**Comment by poscat0x04** [comment]
Nice, Thanks for the clarification.

**Comment by dbaynard** [comment]
@robrix Do you have a timeline yet for 1.1?

**Comment by robrix** [comment]
@dbaynard sorry for the delay. I do, now: today 😊
