### ISSUE TITLE
writing an effect for async

### ISSUE THREAD

**Issue by poscat0x04** [fused-effects/fused-effects#381]
Hi. I'm trying to write an effect for asynchronous IO ([repo](https://github.com/poscat0x04/fused-effects-async)) but I got stuck while implementing the `Effect` instance for [`Asynchronous`](https://github.com/poscat0x04/fused-effects-async/blob/1771c21574c26b8cb80f3f0cd6331af4ef098f41/src/Control/Effect/Async.hs#L12-L14) (can't derive Generic1 because of existential quantification).
To be precise, I got stuck on the continuation part of the `Async` command:
```Haskell
instance Effect Asynchronous where
  thread ::
    (Functor ctx, Monad m) =>
    ctx () ->
    (forall x. ctx (m x) -> n (ctx x)) ->
    Asynchronous m k ->
    Asynchronous n (ctx k)
  thread ctx handler (Async m c) = Async (handler $ m <$ ctx) (\a -> _)
  thread ctx handler (Wait a c) = Wait a (\a -> handler $ c a <$ ctx)
```
I'm starting to wonder if it's even possible to write an Effect instance for Async. Any help would be appreciated.

**Comment by Avi-D-coder** [comment]
Is this relevant https://github.com/fused-effects/fused-effects/issues/357?

**Comment by evanrelf** [comment]
I believe this library shows the only way to use `async` with `fused-effects`: [patrickt/fused-effects-async](https://github.com/patrickt/fused-effects-async)

**Comment by poscat0x04** [comment]
@Avi-D-coder it is indeed very relevant since if I could turn an `Async (ctx a)` into a `ctx (Async a)` I could fill in that hole.

**Comment by poscat0x04** [comment]
@evanrelf I really don't want to unlift everything when using async

**Comment by patrickt** [comment]
Unfortunately, a coherent treatment of an async effect (other than one that wraps the `IO` based functions, a la [this one](https://github.com/patrickt/fused-effects-async/blob/master/src/Control/Effect/Concurrent/Async.hs) is not possible with the current formulations behind fused-effects. Take the example of the state monad: the traditional formulation of the state monad transformer is `s -> m (s, a)`. Using tuples to thread monadic state makes async options problematic: where are those state changes reified? Only monads with no monadic state (basically just `ReaderT IO`) avoid this problem, which means you have to represent stateful variables with IORefs. Unfortunately, the explorations in #296 re. enabling context constraints proved to worsen the situation, as information about monadic state polluted every effectful signature.

Ultimately, the only way to do this right now is for the parameters to `async ` and friends to take `IO` actions, since `IO` means we don't have to promulgate any monadic state. 

Closing as a dup of #293.
